name: CI

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]
  workflow_dispatch: 
    inputs:
      force-run:
        description: 'Force run the workflow'
        required: false
        default: false
        type: boolean

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Set up Minikube
        run: |
          curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          sudo install minikube-linux-amd64 /usr/local/bin/minikube
          minikube start --driver=docker
          minikube status
          echo "KUBECONFIG=$HOME/.kube/config" >> $GITHUB_ENV

      - name: Run tests and generate JUnit report
        run: |
          # Run tests with both default and JUnit reporters
          bun run test --reporter default --reporter junit --outputFile junit-results.xml

      - name: Test Report
        uses: dorny/test-reporter@v2
        if: always()
        with:
          name: Bun Tests # Name of the check run which will be created
          path: junit-results.xml # Path to test results
          reporter: jest-junit # Format of test results (jest-junit is compatible with Bun's JUnit output)
          fail-on-error: true # Fail the workflow if there are test failures

      - name: Verify build works
        run: bun run build

      - name: Clean up kubectl proxy
        if: always()
        run: |
          # Always attempt to kill the proxy process even if previous steps fail
          if [ -n "$KUBECTL_PROXY_PID" ]; then
            echo "Stopping kubectl proxy (PID: $KUBECTL_PROXY_PID)"
            kill $KUBECTL_PROXY_PID || true
          fi

          # Restore the original kubeconfig (optional)
          sed -i 's|http://localhost:8080|https://192.168.49.2:8443|g' ~/.kube/config
